---
- src: calvinbui.ansible_docker
  version: '2.0.0'

- src: calvinbui.ansible_pip
  version: '4.0.0'

- src: calvinbui.ansible_watchtower
  version: '1.0.0'

- src: calvinbui.ansible_home_assistant
  version: '1.0.0'
